site_name: Ivo Sam - Senior Technical Writer
nav:
  - About Me: index.md
  - Experience: experience.md
  - Education: education.md
  - Selected Past Work: past_work.md

theme:
  name: material
  palette:
    primary: red
    accent: indigo
  logo: images/profile_pic.JPG